# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "479c0f4598b92323ac11cc6cfe129112"
name = "launch-ready"
application_url = "https://launch-ready-539004348118.us-central1.run.app"
embedded = true
handle = "launch-ready"

[build]
automatically_update_urls_on_dev = true
dev_store_url = "super-chewy.myshopify.com"

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  uri = "/webhooks/privacy"
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]

  [[webhooks.subscriptions]]
  topics = [ "products/create" ]
  uri = "/webhooks/products/create"

  [[webhooks.subscriptions]]
  topics = [ "app_subscriptions/update" ]
  uri = "/webhooks/app/subscriptions_update"

  [[webhooks.subscriptions]]
  topics = [ "products/update" ]
  uri = "/webhooks/products/update"

  [[webhooks.subscriptions]]
  topics = [ "shop/update" ]
  uri = "/webhooks/shop/update"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_files,write_products"

[auth]
redirect_urls = [
  "https://launch-ready-539004348118.us-central1.run.app/api/auth"
]

[product.metafields.product_score.current_score]
type = "single_line_text_field"
name = "Product Score"
description = "Current calculated score for this product"

[product.metafields.product_score.last_updated]
type = "date_time"
name = "Score Last Updated"
description = "When the product score was last calculated"
